### ISSUE TITLE
Possible problem with Ö

### ISSUE THREAD

**Issue by fnielsen** [zone47/CROTOS#2]
These two items show the same painting: 

http://www.zone47.com/crotos/?q=18600052

http://www.zone47.com/crotos/?q=14632140

Ida with the piano: 

https://commons.wikimedia.org/wiki/File:Hammershoi.jpg

However, one of the should be without the piano. This one: 
https://commons.wikimedia.org/wiki/File:Hammersh%C3%B6i.jpg

I note the difference between o and ö in the two filenames. Perhaps ö is "lost in translation" somewhere?

**Comment by zone47** [comment]
Thank you!
You point a bug which seems indeed caused by an accent-insensitive query.
I will try to fix it this week-end.
PS: paintings of Vilhelm Hammershøi, <3 (discovered for me last year with Wikidata)

**Comment by zone47** [comment]
Fixed. As you guessed the ö was "lost" in accent-insensitive queries.
Thanks!

**Comment by fnielsen** [comment]
I works fine now from my side. Thanks for fixing.
