### ISSUE TITLE
Respect the 'Accept-Language' HTTP header the browsers send

### ISSUE THREAD

**Issue by MaxValue** [zone47/CROTOS#5]
Hi!

I noticed that by default CROTOS displays itself in french even though the user has set its browser language to something different.

So for example my browser sends:
`Accept-Language: en-US,en;q=0.8,de-AT;q=0.6,de-DE;q=0.4,de;q=0.2`

But it still gets displayed in french and I have to manually locate the language menu and set the language myself.

It would be a big benefit for the user if the server does this by itself.

---

I searched for possible places in code (using the string 'fr') where this is set and found some:

- https://github.com/zone47/CROTOS/blob/master/lab/cpt_lg.php#L7
- https://github.com/zone47/CROTOS/blob/master/lab/index.php#L2
- https://github.com/zone47/CROTOS/blob/master/lab/cropper/index.php#L2
- https://github.com/zone47/CROTOS/blob/master/lab/prop_nb.php#L9
- https://github.com/zone47/CROTOS/blob/master/lab/artworks/index.php#L14
- https://github.com/zone47/CROTOS/blob/master/lab/cropper/canevas.php#L37
- https://github.com/zone47/CROTOS/blob/master/lab/cropper/n180.php#L11
- https://github.com/zone47/CROTOS/blob/master/lab/collections.php#L9
- https://github.com/zone47/CROTOS/blob/master/init.php#L24
- https://github.com/zone47/CROTOS/blob/master/ajax_refresh.php#L2
- https://github.com/zone47/CROTOS/blob/master/callisto/index.php#L11

**Comment by zone47** [comment]
Hello MaxValue. Thanks a lot for you message. I must say that i didn't know this possibility to use 'Accept-Language' HTTP header. Indeed it could be very usefull. As you notice, currently, the localization could  only be made by an user choice, we can make better.
As you recommand, I will make this modification as soon as I could.
Best regards

**Comment by zone47** [comment]
Hello MaxValue.
It's fixed now: https://github.com/zone47/CROTOS/commit/4e28f2d7ef628a299e5e91f367d8819998a11812
Thanks for the advice about this very appreciable improvement.
Best regards

**Comment by MaxValue** [comment]
Awesome! Thank you very much for this!
