### ISSUE TITLE
(Feature request) Add jewellery to Crotos?

### ISSUE THREAD

**Issue by trnstlntk** [zone47/CROTOS#6]
Would it be possible to also add all jewellery on Wikidata to Crotos?

See [this query ](https://w.wiki/3Y$)which gives over 1,000 results, many with images. I think it's interesting because we may expect an increasing number of (illustrated) jewellery items on Wikidata because of Structured Data on Commons. 

Thank you for considering this :-) Cheers, Sandra (User:Spinster on Wikimedia)

**Comment by zone47** [comment]
It is done :  http://zone47.com/crotos/?p31=3575260
with pleasure!
Thank you for the suggestion
