### ISSUE TITLE
(Feature request) Add copyright status information to the works on Crotos

### ISSUE THREAD

**Issue by trnstlntk** [zone47/CROTOS#7]
Very recently, Wikidatans have started modelling the copyright status of creative works.

There's the new property Copyright status: https://www.wikidata.org/wiki/Property:P6216
Which is used over 300,000 times already at this point: https://www.wikidata.org/wiki/Property_talk:P6216

Documentation is written here: https://www.wikidata.org/wiki/Help:Copyrights

And here's a query for a selection of artworks that have a copyright status (all of them public domain): https://w.wiki/3Z5

Would it be possible to add this copyright status to **works** on Crotos too, perhaps as an icon symbolizing the copyright status of each work? I know you already indicate the copyright status of the image from Commons, but via the above system it is now also possible to state the copyright status of the underlying artwork.

...

(Some side thoughts about Creative Commons and other licenses:)

I think in the vast majority of cases, the copyright status of works on Crotos will be Public Domain.

As time progresses, there may be some exceptions where works are copyrighted but licensed under a CC or other free content license. I think there is currently no best practice yet for modelling these.

FYI, there are some Wikidata items that have the License property: https://w.wiki/3Z9 but it's possible that the way this is currently modelled may change (e.g. License becoming a qualifier of the Copyrighted copyright status).

I hope this makes sense. Cheers! Sandra

**Comment by zone47** [comment]
Thank you for the suggestion.
The property p6216 has been added. And the copyright status is indicated in the notice.
Crotos harvests almost nothing more than artworks with image or wikipedia page, so a very large majority are public domain. Actually Crotos, is an example of what can be done with public domain.
For information, today on ~200 000 artworks, status, there is:
- 117 770 artworks with claim p6216 "public domain"
- 11 with "copyrighted"
- 1 with "freedom of panorama"
Best regards
